FROM python:3.13-slim

WORKDIR /app

# copiar dependencias
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copiar proyecto
COPY . .

# ejecutar worker
CMD ["python", "worker.py"]